/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface PersistentDigitalAssetInput {
    encryptedPassword: PersistentEncryptedData;
    username: string;
    platform: string;
    category: PersistentCategory;
}
export interface PersistentNominee {
    relationship: PersistentRelationship;
    name: string;
    idProof: PersistentEncryptedData;
    verificationStatus: PersistentVerificationStatus;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PersistentDigitalAsset {
    encryptedPassword: PersistentEncryptedData;
    username: string;
    platform: string;
    category: PersistentCategory;
}
export interface PersistentDeathVerificationRequest {
    status: PersistentDeathVerificationStatus;
    requestId: bigint;
    governmentIdBlob: Uint8Array;
    submittedAt: bigint;
    deathCertificateBlob: Uint8Array;
    heirFullName: string;
    relationshipProofBlob?: Uint8Array;
    deceasedFullName: string;
    relationshipToDeceased: string;
    deceasedEmail: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PersistentLegalVerification {
    status: Variant_pending_approved_rejected;
    auditTrail: Array<string>;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface PersistentEncryptedData {
    blob: ExternalBlob;
    size: bigint;
}
export interface PersistentAccountState {
    alive: boolean;
    timeOfDeath?: Time;
}
export interface PersistentNomineeInput {
    relationship: PersistentRelationship;
    name: string;
    idProof: PersistentEncryptedData;
}
export interface PersistentActivityLog {
    principal: Principal;
    action: string;
    timestamp: Time;
}
export interface PersistentUserProfile {
    name: string;
    encryptedData: PersistentEncryptedData;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum PersistentCategory {
    other = "other",
    cloud = "cloud",
    banking = "banking",
    crypto = "crypto",
    socialMedia = "socialMedia"
}
export enum PersistentDeathVerificationStatus {
    PendingVerification = "PendingVerification",
    Approved = "Approved",
    Rejected = "Rejected"
}
export enum PersistentRelationship {
    legalRepresentative = "legalRepresentative",
    other = "other",
    child = "child",
    sibling = "sibling",
    spouse = "spouse"
}
export enum PersistentVerificationStatus {
    verified = "verified",
    pending = "pending",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_Approved_Rejected {
    Approved = "Approved",
    Rejected = "Rejected"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Adds a digital asset for the caller. Requires authenticated user role.
     */
    addAsset(assetInput: PersistentDigitalAssetInput): Promise<void>;
    /**
     * / Adds a nominee for the caller. Requires authenticated user role.
     */
    addNominee(nomineeInput: PersistentNomineeInput): Promise<void>;
    /**
     * / Admin-only: Approves the legal verification for a given user.
     */
    approveLegalVerification(user: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Returns the account state for the caller. Requires authenticated user role.
     */
    getAccountState(): Promise<PersistentAccountState | null>;
    /**
     * / Admin-only: Returns all activity logs.
     */
    getActivityLogs(): Promise<Array<PersistentActivityLog>>;
    /**
     * / Returns the caller's own digital assets. Requires authenticated user role.
     */
    getAssets(): Promise<Array<PersistentDigitalAsset>>;
    /**
     * / Returns activity logs relevant to the caller (filtered by principal field). Requires authenticated user role.
     */
    getCallerActivityLogs(): Promise<Array<PersistentActivityLog>>;
    getCallerUserProfile(): Promise<PersistentUserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDeathVerificationRequests(): Promise<Array<PersistentDeathVerificationRequest>>;
    /**
     * / Returns the legal verification record for the caller. Requires authenticated user role.
     */
    getLegalVerification(): Promise<PersistentLegalVerification | null>;
    /**
     * / Admin-only: Returns the legal verification record for a given user.
     */
    getLegalVerificationForUser(user: Principal): Promise<PersistentLegalVerification | null>;
    /**
     * / Returns the caller's own nominees. Requires authenticated user role.
     */
    getNominees(): Promise<Array<PersistentNominee>>;
    getUserProfile(user: Principal): Promise<PersistentUserProfile | null>;
    /**
     * / Initiates a legal verification request for the caller (e.g., submitting a death certificate).
     * / Requires authenticated user role.
     */
    initiateLegalVerification(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    /**
     * / Admin-only: Records an access release event for a given user and logs it.
     */
    recordAccessRelease(user: Principal, note: string): Promise<void>;
    /**
     * / Admin-only: Rejects the legal verification for a given user.
     */
    rejectLegalVerification(user: Principal): Promise<void>;
    /**
     * / Removes a digital asset at the given index for the caller. Requires authenticated user role.
     */
    removeAsset(assetIndex: bigint): Promise<void>;
    /**
     * / Removes a nominee at the given index for the caller. Requires authenticated user role.
     */
    removeNominee(nomineeIndex: bigint): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: PersistentUserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    /**
     * / Admin-only: Sets the verification status of a nominee for a given user.
     */
    setNomineeVerificationStatus(user: Principal, nomineeIndex: bigint, status: PersistentVerificationStatus): Promise<void>;
    submitDeathVerificationRequest(deceasedFullName: string, deceasedEmail: string, heirFullName: string, relationshipToDeceased: string, governmentIdBlob: Uint8Array, deathCertificateBlob: Uint8Array, relationshipProofBlob: Uint8Array | null): Promise<bigint>;
    /**
     * / Admin-only: Updates the account state (alive/deceased) for a given user.
     * / Only admins may declare a user deceased, as this triggers controlled access release.
     */
    updateAccountState(user: Principal, alive: boolean): Promise<void>;
    updateDeathVerificationStatus(requestId: bigint, newStatus: Variant_Approved_Rejected): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, ExternalBlob as _ExternalBlob, PersistentAccountState as _PersistentAccountState, PersistentCategory as _PersistentCategory, PersistentDeathVerificationRequest as _PersistentDeathVerificationRequest, PersistentDeathVerificationStatus as _PersistentDeathVerificationStatus, PersistentDigitalAsset as _PersistentDigitalAsset, PersistentDigitalAssetInput as _PersistentDigitalAssetInput, PersistentEncryptedData as _PersistentEncryptedData, PersistentLegalVerification as _PersistentLegalVerification, PersistentNominee as _PersistentNominee, PersistentNomineeInput as _PersistentNomineeInput, PersistentRelationship as _PersistentRelationship, PersistentUserProfile as _PersistentUserProfile, PersistentVerificationStatus as _PersistentVerificationStatus, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAsset(arg0: PersistentDigitalAssetInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAsset(await to_candid_PersistentDigitalAssetInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAsset(await to_candid_PersistentDigitalAssetInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addNominee(arg0: PersistentNomineeInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNominee(await to_candid_PersistentNomineeInput_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNominee(await to_candid_PersistentNomineeInput_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async approveLegalVerification(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveLegalVerification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveLegalVerification(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAccountState(): Promise<PersistentAccountState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountState();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountState();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityLogs(): Promise<Array<PersistentActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogs();
            return result;
        }
    }
    async getAssets(): Promise<Array<PersistentDigitalAsset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssets();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssets();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerActivityLogs(): Promise<Array<PersistentActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerActivityLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerActivityLogs();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<PersistentUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeathVerificationRequests(): Promise<Array<PersistentDeathVerificationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeathVerificationRequests();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeathVerificationRequests();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLegalVerification(): Promise<PersistentLegalVerification | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLegalVerification();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLegalVerification();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLegalVerificationForUser(arg0: Principal): Promise<PersistentLegalVerification | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLegalVerificationForUser(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLegalVerificationForUser(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNominees(): Promise<Array<PersistentNominee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNominees();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNominees();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<PersistentUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async initiateLegalVerification(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateLegalVerification();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateLegalVerification();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordAccessRelease(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAccessRelease(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAccessRelease(arg0, arg1);
            return result;
        }
    }
    async rejectLegalVerification(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectLegalVerification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectLegalVerification(arg0);
            return result;
        }
    }
    async removeAsset(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAsset(arg0);
            return result;
        }
    }
    async removeNominee(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeNominee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeNominee(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: PersistentUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_PersistentUserProfile_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_PersistentUserProfile_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n61(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n61(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setNomineeVerificationStatus(arg0: Principal, arg1: bigint, arg2: PersistentVerificationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNomineeVerificationStatus(arg0, arg1, to_candid_PersistentVerificationStatus_n63(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNomineeVerificationStatus(arg0, arg1, to_candid_PersistentVerificationStatus_n63(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async submitDeathVerificationRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Uint8Array, arg5: Uint8Array, arg6: Uint8Array | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDeathVerificationRequest(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n65(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDeathVerificationRequest(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n65(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateAccountState(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccountState(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccountState(arg0, arg1);
            return result;
        }
    }
    async updateDeathVerificationStatus(arg0: bigint, arg1: Variant_Approved_Rejected): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeathVerificationStatus(arg0, to_candid_variant_n66(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeathVerificationStatus(arg0, to_candid_variant_n66(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PersistentAccountState_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentAccountState): PersistentAccountState {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PersistentCategory_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentCategory): PersistentCategory {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PersistentDeathVerificationRequest_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentDeathVerificationRequest): PersistentDeathVerificationRequest {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_PersistentDeathVerificationStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentDeathVerificationStatus): PersistentDeathVerificationStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_PersistentDigitalAsset_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentDigitalAsset): Promise<PersistentDigitalAsset> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_PersistentEncryptedData_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentEncryptedData): Promise<PersistentEncryptedData> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PersistentLegalVerification_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentLegalVerification): PersistentLegalVerification {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
async function from_candid_PersistentNominee_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentNominee): Promise<PersistentNominee> {
    return await from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_PersistentRelationship_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentRelationship): PersistentRelationship {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
async function from_candid_PersistentUserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentUserProfile): Promise<PersistentUserProfile> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PersistentVerificationStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersistentVerificationStatus): PersistentVerificationStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersistentAccountState]): PersistentAccountState | null {
    return value.length === 0 ? null : from_candid_PersistentAccountState_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersistentUserProfile]): Promise<PersistentUserProfile | null> {
    return value.length === 0 ? null : await from_candid_PersistentUserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersistentLegalVerification]): PersistentLegalVerification | null {
    return value.length === 0 ? null : from_candid_PersistentLegalVerification_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alive: boolean;
    timeOfDeath: [] | [_Time];
}): {
    alive: boolean;
    timeOfDeath?: Time;
} {
    return {
        alive: value.alive,
        timeOfDeath: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.timeOfDeath))
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    encryptedPassword: _PersistentEncryptedData;
    username: string;
    platform: string;
    category: _PersistentCategory;
}): Promise<{
    encryptedPassword: PersistentEncryptedData;
    username: string;
    platform: string;
    category: PersistentCategory;
}> {
    return {
        encryptedPassword: await from_candid_PersistentEncryptedData_n28(_uploadFile, _downloadFile, value.encryptedPassword),
        username: value.username,
        platform: value.platform,
        category: from_candid_PersistentCategory_n31(_uploadFile, _downloadFile, value.category)
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    size: bigint;
}): Promise<{
    blob: ExternalBlob;
    size: bigint;
}> {
    return {
        blob: await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value.blob),
        size: value.size
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    encryptedData: _PersistentEncryptedData;
}): Promise<{
    name: string;
    encryptedData: PersistentEncryptedData;
}> {
    return {
        name: value.name,
        encryptedData: await from_candid_PersistentEncryptedData_n28(_uploadFile, _downloadFile, value.encryptedData)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PersistentDeathVerificationStatus;
    requestId: bigint;
    governmentIdBlob: Uint8Array;
    submittedAt: bigint;
    deathCertificateBlob: Uint8Array;
    heirFullName: string;
    relationshipProofBlob: [] | [Uint8Array];
    deceasedFullName: string;
    relationshipToDeceased: string;
    deceasedEmail: string;
}): {
    status: PersistentDeathVerificationStatus;
    requestId: bigint;
    governmentIdBlob: Uint8Array;
    submittedAt: bigint;
    deathCertificateBlob: Uint8Array;
    heirFullName: string;
    relationshipProofBlob?: Uint8Array;
    deceasedFullName: string;
    relationshipToDeceased: string;
    deceasedEmail: string;
} {
    return {
        status: from_candid_PersistentDeathVerificationStatus_n41(_uploadFile, _downloadFile, value.status),
        requestId: value.requestId,
        governmentIdBlob: value.governmentIdBlob,
        submittedAt: value.submittedAt,
        deathCertificateBlob: value.deathCertificateBlob,
        heirFullName: value.heirFullName,
        relationshipProofBlob: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.relationshipProofBlob)),
        deceasedFullName: value.deceasedFullName,
        relationshipToDeceased: value.relationshipToDeceased,
        deceasedEmail: value.deceasedEmail
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    auditTrail: Array<string>;
}): {
    status: Variant_pending_approved_rejected;
    auditTrail: Array<string>;
} {
    return {
        status: from_candid_variant_n47(_uploadFile, _downloadFile, value.status),
        auditTrail: value.auditTrail
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    relationship: _PersistentRelationship;
    name: string;
    idProof: _PersistentEncryptedData;
    verificationStatus: _PersistentVerificationStatus;
}): Promise<{
    relationship: PersistentRelationship;
    name: string;
    idProof: PersistentEncryptedData;
    verificationStatus: PersistentVerificationStatus;
}> {
    return {
        relationship: from_candid_PersistentRelationship_n51(_uploadFile, _downloadFile, value.relationship),
        name: value.name,
        idProof: await from_candid_PersistentEncryptedData_n28(_uploadFile, _downloadFile, value.idProof),
        verificationStatus: from_candid_PersistentVerificationStatus_n53(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n58(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    cloud: null;
} | {
    banking: null;
} | {
    crypto: null;
} | {
    socialMedia: null;
}): PersistentCategory {
    return "other" in value ? PersistentCategory.other : "cloud" in value ? PersistentCategory.cloud : "banking" in value ? PersistentCategory.banking : "crypto" in value ? PersistentCategory.crypto : "socialMedia" in value ? PersistentCategory.socialMedia : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PendingVerification: null;
} | {
    Approved: null;
} | {
    Rejected: null;
}): PersistentDeathVerificationStatus {
    return "PendingVerification" in value ? PersistentDeathVerificationStatus.PendingVerification : "Approved" in value ? PersistentDeathVerificationStatus.Approved : "Rejected" in value ? PersistentDeathVerificationStatus.Rejected : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    legalRepresentative: null;
} | {
    other: null;
} | {
    child: null;
} | {
    sibling: null;
} | {
    spouse: null;
}): PersistentRelationship {
    return "legalRepresentative" in value ? PersistentRelationship.legalRepresentative : "other" in value ? PersistentRelationship.other : "child" in value ? PersistentRelationship.child : "sibling" in value ? PersistentRelationship.sibling : "spouse" in value ? PersistentRelationship.spouse : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
}): PersistentVerificationStatus {
    return "verified" in value ? PersistentVerificationStatus.verified : "pending" in value ? PersistentVerificationStatus.pending : "rejected" in value ? PersistentVerificationStatus.rejected : value;
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PersistentDigitalAsset>): Promise<Array<PersistentDigitalAsset>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PersistentDigitalAsset_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PersistentDeathVerificationRequest>): Array<PersistentDeathVerificationRequest> {
    return value.map((x)=>from_candid_PersistentDeathVerificationRequest_n39(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PersistentNominee>): Promise<Array<PersistentNominee>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PersistentNominee_n49(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n56(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PersistentCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentCategory): _PersistentCategory {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_PersistentDigitalAssetInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentDigitalAssetInput): Promise<_PersistentDigitalAssetInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_PersistentEncryptedData_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentEncryptedData): Promise<_PersistentEncryptedData> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_PersistentNomineeInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentNomineeInput): Promise<_PersistentNomineeInput> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_PersistentRelationship_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentRelationship): _PersistentRelationship {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_PersistentUserProfile_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentUserProfile): Promise<_PersistentUserProfile> {
    return await to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_PersistentVerificationStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentVerificationStatus): _PersistentVerificationStatus {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Uint8Array | null): [] | [Uint8Array] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    size: bigint;
}): Promise<{
    blob: _ExternalBlob;
    size: bigint;
}> {
    return {
        blob: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.blob),
        size: value.size
    };
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    relationship: PersistentRelationship;
    name: string;
    idProof: PersistentEncryptedData;
}): Promise<{
    relationship: _PersistentRelationship;
    name: string;
    idProof: _PersistentEncryptedData;
}> {
    return {
        relationship: to_candid_PersistentRelationship_n17(_uploadFile, _downloadFile, value.relationship),
        name: value.name,
        idProof: await to_candid_PersistentEncryptedData_n10(_uploadFile, _downloadFile, value.idProof)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    encryptedData: PersistentEncryptedData;
}): Promise<{
    name: string;
    encryptedData: _PersistentEncryptedData;
}> {
    return {
        name: value.name,
        encryptedData: await to_candid_PersistentEncryptedData_n10(_uploadFile, _downloadFile, value.encryptedData)
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    encryptedPassword: PersistentEncryptedData;
    username: string;
    platform: string;
    category: PersistentCategory;
}): Promise<{
    encryptedPassword: _PersistentEncryptedData;
    username: string;
    platform: string;
    category: _PersistentCategory;
}> {
    return {
        encryptedPassword: await to_candid_PersistentEncryptedData_n10(_uploadFile, _downloadFile, value.encryptedPassword),
        username: value.username,
        platform: value.platform,
        category: to_candid_PersistentCategory_n13(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentCategory): {
    other: null;
} | {
    cloud: null;
} | {
    banking: null;
} | {
    crypto: null;
} | {
    socialMedia: null;
} {
    return value == PersistentCategory.other ? {
        other: null
    } : value == PersistentCategory.cloud ? {
        cloud: null
    } : value == PersistentCategory.banking ? {
        banking: null
    } : value == PersistentCategory.crypto ? {
        crypto: null
    } : value == PersistentCategory.socialMedia ? {
        socialMedia: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentRelationship): {
    legalRepresentative: null;
} | {
    other: null;
} | {
    child: null;
} | {
    sibling: null;
} | {
    spouse: null;
} {
    return value == PersistentRelationship.legalRepresentative ? {
        legalRepresentative: null
    } : value == PersistentRelationship.other ? {
        other: null
    } : value == PersistentRelationship.child ? {
        child: null
    } : value == PersistentRelationship.sibling ? {
        sibling: null
    } : value == PersistentRelationship.spouse ? {
        spouse: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_approved_rejected): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == Variant_pending_approved_rejected.pending ? {
        pending: null
    } : value == Variant_pending_approved_rejected.approved ? {
        approved: null
    } : value == Variant_pending_approved_rejected.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersistentVerificationStatus): {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
} {
    return value == PersistentVerificationStatus.verified ? {
        verified: null
    } : value == PersistentVerificationStatus.pending ? {
        pending: null
    } : value == PersistentVerificationStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Approved_Rejected): {
    Approved: null;
} | {
    Rejected: null;
} {
    return value == Variant_Approved_Rejected.Approved ? {
        Approved: null
    } : value == Variant_Approved_Rejected.Rejected ? {
        Rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
