/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface PersistentAccountState {
  'alive' : boolean,
  'timeOfDeath' : [] | [Time],
}
export interface PersistentActivityLog {
  'principal' : Principal,
  'action' : string,
  'timestamp' : Time,
}
export type PersistentCategory = { 'other' : null } |
  { 'cloud' : null } |
  { 'banking' : null } |
  { 'crypto' : null } |
  { 'socialMedia' : null };
export interface PersistentDeathVerificationRequest {
  'status' : PersistentDeathVerificationStatus,
  'requestId' : bigint,
  'governmentIdBlob' : Uint8Array,
  'submittedAt' : bigint,
  'deathCertificateBlob' : Uint8Array,
  'heirFullName' : string,
  'relationshipProofBlob' : [] | [Uint8Array],
  'deceasedFullName' : string,
  'relationshipToDeceased' : string,
  'deceasedEmail' : string,
}
export type PersistentDeathVerificationStatus = {
    'PendingVerification' : null
  } |
  { 'Approved' : null } |
  { 'Rejected' : null };
export interface PersistentDigitalAsset {
  'encryptedPassword' : PersistentEncryptedData,
  'username' : string,
  'platform' : string,
  'category' : PersistentCategory,
}
export interface PersistentDigitalAssetInput {
  'encryptedPassword' : PersistentEncryptedData,
  'username' : string,
  'platform' : string,
  'category' : PersistentCategory,
}
export interface PersistentEncryptedData {
  'blob' : ExternalBlob,
  'size' : bigint,
}
export interface PersistentLegalVerification {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'auditTrail' : Array<string>,
}
export interface PersistentNominee {
  'relationship' : PersistentRelationship,
  'name' : string,
  'idProof' : PersistentEncryptedData,
  'verificationStatus' : PersistentVerificationStatus,
}
export interface PersistentNomineeInput {
  'relationship' : PersistentRelationship,
  'name' : string,
  'idProof' : PersistentEncryptedData,
}
export type PersistentRelationship = { 'legalRepresentative' : null } |
  { 'other' : null } |
  { 'child' : null } |
  { 'sibling' : null } |
  { 'spouse' : null };
export interface PersistentUserProfile {
  'name' : string,
  'encryptedData' : PersistentEncryptedData,
}
export type PersistentVerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Adds a digital asset for the caller. Requires authenticated user role.
   */
  'addAsset' : ActorMethod<[PersistentDigitalAssetInput], undefined>,
  /**
   * / Adds a nominee for the caller. Requires authenticated user role.
   */
  'addNominee' : ActorMethod<[PersistentNomineeInput], undefined>,
  /**
   * / Admin-only: Approves the legal verification for a given user.
   */
  'approveLegalVerification' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Returns the account state for the caller. Requires authenticated user role.
   */
  'getAccountState' : ActorMethod<[], [] | [PersistentAccountState]>,
  /**
   * / Admin-only: Returns all activity logs.
   */
  'getActivityLogs' : ActorMethod<[], Array<PersistentActivityLog>>,
  /**
   * / Returns the caller's own digital assets. Requires authenticated user role.
   */
  'getAssets' : ActorMethod<[], Array<PersistentDigitalAsset>>,
  /**
   * / Returns activity logs relevant to the caller (filtered by principal field). Requires authenticated user role.
   */
  'getCallerActivityLogs' : ActorMethod<[], Array<PersistentActivityLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PersistentUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeathVerificationRequests' : ActorMethod<
    [],
    Array<PersistentDeathVerificationRequest>
  >,
  /**
   * / Returns the legal verification record for the caller. Requires authenticated user role.
   */
  'getLegalVerification' : ActorMethod<[], [] | [PersistentLegalVerification]>,
  /**
   * / Admin-only: Returns the legal verification record for a given user.
   */
  'getLegalVerificationForUser' : ActorMethod<
    [Principal],
    [] | [PersistentLegalVerification]
  >,
  /**
   * / Returns the caller's own nominees. Requires authenticated user role.
   */
  'getNominees' : ActorMethod<[], Array<PersistentNominee>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PersistentUserProfile]>,
  /**
   * / Initiates a legal verification request for the caller (e.g., submitting a death certificate).
   * / Requires authenticated user role.
   */
  'initiateLegalVerification' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  /**
   * / Admin-only: Records an access release event for a given user and logs it.
   */
  'recordAccessRelease' : ActorMethod<[Principal, string], undefined>,
  /**
   * / Admin-only: Rejects the legal verification for a given user.
   */
  'rejectLegalVerification' : ActorMethod<[Principal], undefined>,
  /**
   * / Removes a digital asset at the given index for the caller. Requires authenticated user role.
   */
  'removeAsset' : ActorMethod<[bigint], undefined>,
  /**
   * / Removes a nominee at the given index for the caller. Requires authenticated user role.
   */
  'removeNominee' : ActorMethod<[bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[PersistentUserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  /**
   * / Admin-only: Sets the verification status of a nominee for a given user.
   */
  'setNomineeVerificationStatus' : ActorMethod<
    [Principal, bigint, PersistentVerificationStatus],
    undefined
  >,
  'submitDeathVerificationRequest' : ActorMethod<
    [string, string, string, string, Uint8Array, Uint8Array, [] | [Uint8Array]],
    bigint
  >,
  /**
   * / Admin-only: Updates the account state (alive/deceased) for a given user.
   * / Only admins may declare a user deceased, as this triggers controlled access release.
   */
  'updateAccountState' : ActorMethod<[Principal, boolean], undefined>,
  'updateDeathVerificationStatus' : ActorMethod<
    [bigint, { 'Approved' : null } | { 'Rejected' : null }],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];