/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PersistentEncryptedData = IDL.Record({
  'blob' : ExternalBlob,
  'size' : IDL.Nat,
});
export const PersistentCategory = IDL.Variant({
  'other' : IDL.Null,
  'cloud' : IDL.Null,
  'banking' : IDL.Null,
  'crypto' : IDL.Null,
  'socialMedia' : IDL.Null,
});
export const PersistentDigitalAssetInput = IDL.Record({
  'encryptedPassword' : PersistentEncryptedData,
  'username' : IDL.Text,
  'platform' : IDL.Text,
  'category' : PersistentCategory,
});
export const PersistentRelationship = IDL.Variant({
  'legalRepresentative' : IDL.Null,
  'other' : IDL.Null,
  'child' : IDL.Null,
  'sibling' : IDL.Null,
  'spouse' : IDL.Null,
});
export const PersistentNomineeInput = IDL.Record({
  'relationship' : PersistentRelationship,
  'name' : IDL.Text,
  'idProof' : PersistentEncryptedData,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const PersistentAccountState = IDL.Record({
  'alive' : IDL.Bool,
  'timeOfDeath' : IDL.Opt(Time),
});
export const PersistentActivityLog = IDL.Record({
  'principal' : IDL.Principal,
  'action' : IDL.Text,
  'timestamp' : Time,
});
export const DocumentStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const DocumentType = IDL.Variant({
  'idProof' : IDL.Null,
  'deathCertificate' : IDL.Null,
  'relationshipProof' : IDL.Null,
});
export const DocumentMetadata = IDL.Record({
  'id' : IDL.Nat,
  'status' : DocumentStatus,
  'verificationTime' : IDL.Opt(Time),
  'submitter' : IDL.Principal,
  'blob' : ExternalBlob,
  'adminVerifier' : IDL.Opt(IDL.Principal),
  'adminNote' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'docType' : DocumentType,
});
export const PersistentDigitalAsset = IDL.Record({
  'encryptedPassword' : PersistentEncryptedData,
  'username' : IDL.Text,
  'platform' : IDL.Text,
  'category' : PersistentCategory,
});
export const PersistentUserProfile = IDL.Record({
  'name' : IDL.Text,
  'encryptedData' : PersistentEncryptedData,
});
export const PersistentDeathVerificationStatus = IDL.Variant({
  'PendingVerification' : IDL.Null,
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
});
export const PersistentDeathVerificationRequest = IDL.Record({
  'status' : PersistentDeathVerificationStatus,
  'requestId' : IDL.Nat,
  'governmentIdBlob' : IDL.Vec(IDL.Nat8),
  'submittedAt' : IDL.Int,
  'deathCertificateBlob' : IDL.Vec(IDL.Nat8),
  'heirFullName' : IDL.Text,
  'relationshipProofBlob' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'deceasedFullName' : IDL.Text,
  'relationshipToDeceased' : IDL.Text,
  'deceasedEmail' : IDL.Text,
});
export const PersistentLegalVerification = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'auditTrail' : IDL.Vec(IDL.Text),
});
export const PersistentVerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PersistentNominee = IDL.Record({
  'relationship' : PersistentRelationship,
  'name' : IDL.Text,
  'idProof' : PersistentEncryptedData,
  'verificationStatus' : PersistentVerificationStatus,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAsset' : IDL.Func([PersistentDigitalAssetInput], [], []),
  'addNominee' : IDL.Func([PersistentNomineeInput], [], []),
  'approveLegalVerification' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAccountState' : IDL.Func(
      [],
      [IDL.Opt(PersistentAccountState)],
      ['query'],
    ),
  'getActivityLogs' : IDL.Func([], [IDL.Vec(PersistentActivityLog)], ['query']),
  'getAllDocumentsWithMetadata' : IDL.Func(
      [],
      [IDL.Vec(DocumentMetadata)],
      ['query'],
    ),
  'getAssets' : IDL.Func([], [IDL.Vec(PersistentDigitalAsset)], ['query']),
  'getCallerActivityLogs' : IDL.Func(
      [],
      [IDL.Vec(PersistentActivityLog)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(PersistentUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeathVerificationRequests' : IDL.Func(
      [],
      [IDL.Vec(PersistentDeathVerificationRequest)],
      ['query'],
    ),
  'getLegalVerification' : IDL.Func(
      [],
      [IDL.Opt(PersistentLegalVerification)],
      ['query'],
    ),
  'getLegalVerificationForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PersistentLegalVerification)],
      ['query'],
    ),
  'getNominees' : IDL.Func([], [IDL.Vec(PersistentNominee)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PersistentUserProfile)],
      ['query'],
    ),
  'getUserSubmittedDocuments' : IDL.Func(
      [],
      [IDL.Vec(DocumentMetadata)],
      ['query'],
    ),
  'initiateLegalVerification' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'recordAccessRelease' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'rejectLegalVerification' : IDL.Func([IDL.Principal], [], []),
  'removeAsset' : IDL.Func([IDL.Nat], [], []),
  'removeNominee' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([PersistentUserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setNomineeVerificationStatus' : IDL.Func(
      [IDL.Principal, IDL.Nat, PersistentVerificationStatus],
      [],
      [],
    ),
  'submitDeathVerificationRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat8),
        IDL.Vec(IDL.Nat8),
        IDL.Opt(IDL.Vec(IDL.Nat8)),
      ],
      [IDL.Nat],
      [],
    ),
  'submitDocument' : IDL.Func([DocumentType, ExternalBlob], [IDL.Nat], []),
  'updateAccountState' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'updateDeathVerificationStatus' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'Approved' : IDL.Null, 'Rejected' : IDL.Null })],
      [],
      [],
    ),
  'verifyDocument' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PersistentEncryptedData = IDL.Record({
    'blob' : ExternalBlob,
    'size' : IDL.Nat,
  });
  const PersistentCategory = IDL.Variant({
    'other' : IDL.Null,
    'cloud' : IDL.Null,
    'banking' : IDL.Null,
    'crypto' : IDL.Null,
    'socialMedia' : IDL.Null,
  });
  const PersistentDigitalAssetInput = IDL.Record({
    'encryptedPassword' : PersistentEncryptedData,
    'username' : IDL.Text,
    'platform' : IDL.Text,
    'category' : PersistentCategory,
  });
  const PersistentRelationship = IDL.Variant({
    'legalRepresentative' : IDL.Null,
    'other' : IDL.Null,
    'child' : IDL.Null,
    'sibling' : IDL.Null,
    'spouse' : IDL.Null,
  });
  const PersistentNomineeInput = IDL.Record({
    'relationship' : PersistentRelationship,
    'name' : IDL.Text,
    'idProof' : PersistentEncryptedData,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const PersistentAccountState = IDL.Record({
    'alive' : IDL.Bool,
    'timeOfDeath' : IDL.Opt(Time),
  });
  const PersistentActivityLog = IDL.Record({
    'principal' : IDL.Principal,
    'action' : IDL.Text,
    'timestamp' : Time,
  });
  const DocumentStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const DocumentType = IDL.Variant({
    'idProof' : IDL.Null,
    'deathCertificate' : IDL.Null,
    'relationshipProof' : IDL.Null,
  });
  const DocumentMetadata = IDL.Record({
    'id' : IDL.Nat,
    'status' : DocumentStatus,
    'verificationTime' : IDL.Opt(Time),
    'submitter' : IDL.Principal,
    'blob' : ExternalBlob,
    'adminVerifier' : IDL.Opt(IDL.Principal),
    'adminNote' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'docType' : DocumentType,
  });
  const PersistentDigitalAsset = IDL.Record({
    'encryptedPassword' : PersistentEncryptedData,
    'username' : IDL.Text,
    'platform' : IDL.Text,
    'category' : PersistentCategory,
  });
  const PersistentUserProfile = IDL.Record({
    'name' : IDL.Text,
    'encryptedData' : PersistentEncryptedData,
  });
  const PersistentDeathVerificationStatus = IDL.Variant({
    'PendingVerification' : IDL.Null,
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
  });
  const PersistentDeathVerificationRequest = IDL.Record({
    'status' : PersistentDeathVerificationStatus,
    'requestId' : IDL.Nat,
    'governmentIdBlob' : IDL.Vec(IDL.Nat8),
    'submittedAt' : IDL.Int,
    'deathCertificateBlob' : IDL.Vec(IDL.Nat8),
    'heirFullName' : IDL.Text,
    'relationshipProofBlob' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'deceasedFullName' : IDL.Text,
    'relationshipToDeceased' : IDL.Text,
    'deceasedEmail' : IDL.Text,
  });
  const PersistentLegalVerification = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'auditTrail' : IDL.Vec(IDL.Text),
  });
  const PersistentVerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PersistentNominee = IDL.Record({
    'relationship' : PersistentRelationship,
    'name' : IDL.Text,
    'idProof' : PersistentEncryptedData,
    'verificationStatus' : PersistentVerificationStatus,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAsset' : IDL.Func([PersistentDigitalAssetInput], [], []),
    'addNominee' : IDL.Func([PersistentNomineeInput], [], []),
    'approveLegalVerification' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAccountState' : IDL.Func(
        [],
        [IDL.Opt(PersistentAccountState)],
        ['query'],
      ),
    'getActivityLogs' : IDL.Func(
        [],
        [IDL.Vec(PersistentActivityLog)],
        ['query'],
      ),
    'getAllDocumentsWithMetadata' : IDL.Func(
        [],
        [IDL.Vec(DocumentMetadata)],
        ['query'],
      ),
    'getAssets' : IDL.Func([], [IDL.Vec(PersistentDigitalAsset)], ['query']),
    'getCallerActivityLogs' : IDL.Func(
        [],
        [IDL.Vec(PersistentActivityLog)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(PersistentUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeathVerificationRequests' : IDL.Func(
        [],
        [IDL.Vec(PersistentDeathVerificationRequest)],
        ['query'],
      ),
    'getLegalVerification' : IDL.Func(
        [],
        [IDL.Opt(PersistentLegalVerification)],
        ['query'],
      ),
    'getLegalVerificationForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PersistentLegalVerification)],
        ['query'],
      ),
    'getNominees' : IDL.Func([], [IDL.Vec(PersistentNominee)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PersistentUserProfile)],
        ['query'],
      ),
    'getUserSubmittedDocuments' : IDL.Func(
        [],
        [IDL.Vec(DocumentMetadata)],
        ['query'],
      ),
    'initiateLegalVerification' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'recordAccessRelease' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'rejectLegalVerification' : IDL.Func([IDL.Principal], [], []),
    'removeAsset' : IDL.Func([IDL.Nat], [], []),
    'removeNominee' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([PersistentUserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setNomineeVerificationStatus' : IDL.Func(
        [IDL.Principal, IDL.Nat, PersistentVerificationStatus],
        [],
        [],
      ),
    'submitDeathVerificationRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat8),
          IDL.Vec(IDL.Nat8),
          IDL.Opt(IDL.Vec(IDL.Nat8)),
        ],
        [IDL.Nat],
        [],
      ),
    'submitDocument' : IDL.Func([DocumentType, ExternalBlob], [IDL.Nat], []),
    'updateAccountState' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'updateDeathVerificationStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({ 'Approved' : IDL.Null, 'Rejected' : IDL.Null }),
        ],
        [],
        [],
      ),
    'verifyDocument' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };